### ISSUE TITLE
Cleanup: The business owner toggle does not update it's state 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/ogp-payroll#50]
When selecting yes or no, the states remain active. 
<img width="706" alt="screen shot 2016-04-22 at 3 33 01 pm" src="https://cloud.githubusercontent.com/assets/15899668/14756621/b7319664-089f-11e6-8be3-ba8e5e26c954.png">

**Comment by acolter** [comment]
I think we can probably get rid of the toggle, to be honest. There's already a way to add a work classification that's not on the contract. An owner, for example, could just add "Owner" or even "Carpenter, Owner" if they wanted to get more specific. If you add a work classification this way, you'd also add the rate by hand (or not, in the case of owners, since they only have to report their hours, not their rates.)
